#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Checking Your Code Before Committing'
echo 'Just waiting ...'

#fix & format
npx lint-staged

# Check ESLint Standards
npm run lint && (
  echo '🎉🎉🎉🎉 Greattt, there is no error in your code... Ready to commit. ✨🚀🏄‍♂️🍻'
) || (
  echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌'
  echo 'Run npm run lint / yarn lint, add changes and try commit again.';
  false;
)